[tool.poetry]
name = "repl_python3_MalwareDatabase-1"
version = "0.1.0"
description = ""
authors = ["kirigizakazutov <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
PyVirtualDisplay = "^2.2"
selenium = "^4.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
